<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>csl</string>
	</array>
	<key>name</key>
	<string>Coral (CSL)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#csl</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@[^ (]+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.annotation.coral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation-arguments.begin.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation-arguments.end.coral</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.annotation.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.other.key.coral</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.coral</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\w*)\s*(=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#values</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.property.coral</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>@\w*</string>
					<key>name</key>
					<string>storage.type.annotation.coral</string>
				</dict>
			</array>
		</dict>
		<key>class-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#annotation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cpp-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#port</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.coral</string>
				</dict>
			</array>
		</dict>
		<key>class-spec</key>
		<dict>
			<key>begin</key>
			<string>(?=(?:component|interface|native class|struct)\s+\w+)</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.class.end.coral</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.type.coral</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.class.coral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.coral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(component|interface|enum|native class|struct)\s+(\w+)</string>
					<key>name</key>
					<string>meta.type.identifier.coral</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(extends)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.extends.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\{)</string>
					<key>name</key>
					<string>meta.type.extends.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:\w+\.)*\w+</string>
							<key>name</key>
							<string>entity.other.inherited-class.coral</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.type.body.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#class-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^\s*(---)\s*$</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.yaml.coral</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\*/)</string>
							<key>name</key>
							<string>meta.doc.embedded.yaml.coral</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#doc-yaml</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#doc-markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*$\n?</string>
					<key>name</key>
					<string>comment.block.documentation.coral</string>
				</dict>
			</array>
		</dict>
		<key>cpp-block</key>
		<dict>
			<key>begin</key>
			<string>(&lt;c\+\+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.cpp.coral</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(c\+\+&gt;)</string>
			<key>name</key>
			<string>meta.type.cppblock.coral</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<key>csl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#annotation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum-spec</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class-spec</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.class.coral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.coral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(exception)\s+(\w+)</string>
					<key>name</key>
					<string>meta.exception.coral</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.coral</string>
				</dict>
			</array>
		</dict>
		<key>doc-markdown</key>
		<dict>
			<key>comment</key>
			<string>Basic Markdown highlighting. We use a single-color scheme in order not to distract the viewer too much from the code.
</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*~~~</string>
					<key>comment</key>
					<string>code blocks</string>
					<key>end</key>
					<string>(?:^\s~~~|(?=\*/))</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(?:#{1,6})(?!#)\s*(?=\S)</string>
					<key>comment</key>
					<string>single-line section headings</string>
					<key>end</key>
					<string>\s*(?:#+|$\n?)</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>coral member refs</string>
					<key>match</key>
					<string>\#\w+\b</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>horizontal rules</string>
					<key>match</key>
					<string>^\s*[_*-]\s*[_*-]\s*[_*-](?:\s*[_*-]+)*\s*$</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>lists and blockquotes</string>
					<key>match</key>
					<string>^\s*(?:[&gt;*+-]|[0-9]+\.)(?=\s)</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>inline link/image</string>
					<key>match</key>
					<string>\!?\[[^\]]+\]\([^\)]+\)</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>ref link/image</string>
					<key>match</key>
					<string>\!?\[[^\]]+\]\s?\[[^\]]*\]</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>link definitions</string>
					<key>match</key>
					<string>\[[^\]]+\]:\s*\S.*$</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>auto links and HTML tags</string>
					<key>match</key>
					<string>&lt;.*&gt;</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>emphasis, bold, code</string>
					<key>match</key>
					<string>(?&lt;!\\)(\*\*?|__?|``?)([\w\*_`]+|.+?)(\1)</string>
					<key>name</key>
					<string>keyword.other.documentation.coral</string>
				</dict>
			</array>
		</dict>
		<key>doc-yaml</key>
		<dict>
			<key>comment</key>
			<string>simple YAML highlighter</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\s*)(?:(-)|(?:(-\s*)?(\w+\s*(:))))\s*(\||&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entry.yaml.coral</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entry.yaml.coral</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.yaml.coral</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.yaml.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!^\1)|^(?=\1(-|\w+\s*:)|#|\*/)</string>
					<key>name</key>
					<string>string.unquoted.block.yaml.coral</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entry.yaml.coral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.coral</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.yaml.coral</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entry.yaml.coral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:(?:(-\s*)?(\w+\s*(:)))|(-))\s*((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\s*$</string>
					<key>name</key>
					<string>constant.numeric.yaml.coral</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entry.yaml.coral</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.yaml.coral</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.yaml.coral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.yaml.coral</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.yaml.coral</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entry.yaml.coral</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.yaml.coral</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.yaml.coral</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.yaml.coral</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.yaml.coral</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.yaml.coral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:(?:(-\s*)?(\w+\s*(:)))|(-))\s*(?:((")[^"]*("))|((')[^']*('))|([^,{}&amp;#\[\]]+))\s*</string>
					<key>name</key>
					<string>string.unquoted.yaml.coral</string>
				</dict>
			</array>
		</dict>
		<key>enum-spec</key>
		<dict>
			<key>begin</key>
			<string>(enum)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.class.coral</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.coral</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.enum.coral</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\w+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.symbol.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|}|/)</string>
					<key>name</key>
					<string>meta.enum.coral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>field</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(readonly)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.readonly.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.class.field.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-z]\w*</string>
							<key>name</key>
							<string>variable.other.readonly.instance.coral</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.class.field.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-z]\w*</string>
							<key>name</key>
							<string>variable.other.readwrite.instance.coral</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import.coral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.import.coral</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.coral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(import)\b(?:\s*([^ ;$]+)\s*(;)?)?</string>
					<key>name</key>
					<string>meta.import.coral</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>(?=\w+\s+\w+\s*\()</string>
			<key>end</key>
			<string>(?=;)</string>
			<key>name</key>
			<string>meta.method.coral</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\w.*\s+\w+\s*\()</string>
					<key>end</key>
					<string>(?=\w+\s*\()</string>
					<key>name</key>
					<string>meta.method.return-type.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.method.identifier.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameter</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>raises</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.raises.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.method.raises.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type-name</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:inout|in|out)\b</string>
					<key>name</key>
					<string>storage.modifier.inout.coral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>variable.parameter.coral</string>
				</dict>
			</array>
		</dict>
		<key>port</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(provides)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.provides.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.component.provides.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type-name</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-z]\w*</string>
							<key>name</key>
							<string>variable.other.readonly.instance.coral</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(receives)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.receives.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.component.receives.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type-name</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-z]\w*</string>
							<key>name</key>
							<string>variable.other.readwrite.instance.coral</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.coral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.coral</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.coral</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.coral</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[\]</string>
					<key>name</key>
					<string>constant.other.array.coral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-base</string>
				</dict>
			</array>
		</dict>
		<key>type-base</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:any|bool|double|float|int8|int16|int32|string|uint8|uint16|uint32|void)\b</string>
					<key>name</key>
					<string>storage.type.coral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>type-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.other.coral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:[a-z]\w*(\.))*[A-Z]\w*\b</string>
					<key>name</key>
					<string>support.class.coral</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.coral</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
					<key>name</key>
					<string>constant.numeric.coral</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.coral</string>
	<key>uuid</key>
	<string>a68ef5ba-852a-4c5c-b94f-e09794cb051a</string>
</dict>
</plist>
